language: cpp

compiler: gcc

matrix:
  include:
    - os: linux


before_install:
- echo $LANG
- echo $LC_ALL


install:
 # - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script: #cmake . 
    - bash runLinux.sh
    #- PowerShell -File run.ps1