language: cpp

compiler: gcc

matrix:
  include:
    - os: linux


before_install:
- echo "Before install"



install:
 # - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script: #cmake . 
    - dos2unix runLinux.sh
    - bash runLinux.sh
    #- PowerShell -File run.ps1